default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Bella2174!
  host: localhost

development:
  <<: *default
  database: z_fc_development

test:
  <<: *default
  database: z_fc_test

production:
  <<: *default
  database: z_fc_production
